name: <test>
on:
  push:
    paths: [.github/workflows/test.yml]
  pull_request:
    paths: [.github/workflows/test.yml]
jobs:
  
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        ruby-version: ['3', '2.0']
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
    
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Print FFI Version
      run: ruby -e 'require 'ffi'; puts FFI::VERSION'
